import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import FaultyTerminal from "@/components/ui/faulty-terminal";

const rajdhani = Rajdhani({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "GLYTCH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rajdhani.variable} antialiased`}>
        <Header />
        <div className="fixed inset-0 z-0 pointer-events-none" aria-hidden>
          <FaultyTerminal />
        </div>
        {children}
      </body>
    </html>
  );
}
